#!/usr/bin/env python3
"""Build three isolated MiniMax H3 ComfyUI workflows from the checked-in template.

This script never changes the source workflow.  It rewrites only files below the
project's ``comfyui_workflows`` directory unless an explicit output directory is
passed on the command line.
"""

from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any, Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "comfyui_workflows"
DEFAULT_SOURCE = (
    DEFAULT_OUTPUT_DIR
    / "MiniMax_H3_I2VA_INT8_Turbo8_HQ_9x16_7s_1080p.json"
)

MODEL_FRAMES = 175
OUTPUT_FRAMES = 168
FPS = 24
DURATION_SECONDS = 7.0
SELECTED_INDICES = [
    (index * (MODEL_FRAMES - 1) + (OUTPUT_FRAMES - 1) // 2)
    // (OUTPUT_FRAMES - 1)
    for index in range(OUTPUT_FRAMES)
]

OUTPUT_FILENAMES = {
    "T2VA": "MiniMax_H3_T2VA_INT8_Turbo8_HQ_9x16_7s_1080p.json",
    "I2VA": "MiniMax_H3_I2VA_INT8_Turbo8_HQ_9x16_7s_1080p.json",
    "FL2VA": "MiniMax_H3_FL2VA_INT8_Turbo8_HQ_9x16_7s_1080p.json",
}

GENERIC_PROMPTS = {
    "T2VA": """integrated_multimodal_description: [Shot 1] Cinematic video placeholder. Paste the complete T2VA prompt generated by H3 Prompt Studio here.

overall_soundscape: Replace this placeholder with the generated environmental and physical sound description.

non_diegetic_music: N/A""",
    "I2VA": """For the target video, at 0.00 seconds into the target video, <Picture 1> (from [Shot 1]) is fully referenced.

integrated_multimodal_description: [Shot 1] Cinematic video placeholder beginning from <Picture 1>. Paste the complete I2VA prompt generated by H3 Prompt Studio here.

overall_soundscape: Replace this placeholder with the generated environmental and physical sound description.

non_diegetic_music: N/A""",
    "FL2VA": """How the reference pictures align with the target video — Picture 1 (from Shot 1) aligns with the 0.00-second mark of the target video; Picture 2 (from Shot 1) aligns with the 7.00-second mark of the target video.

integrated_multimodal_description: [Shot 1] Cinematic video placeholder connecting Picture 1 continuously to Picture 2. Paste the complete FL2VA prompt generated by H3 Prompt Studio here.

overall_soundscape: Replace this placeholder with the generated environmental and physical sound description.

non_diegetic_music: N/A""",
}


def _node(nodes: list[dict[str, Any]], node_id: int) -> dict[str, Any]:
    for item in nodes:
        if item.get("id") == node_id:
            return item
    raise ValueError(f"Missing node {node_id}")


def _input_slot(node: dict[str, Any], name: str) -> int:
    for index, item in enumerate(node.get("inputs", [])):
        if item.get("name") == name:
            return index
    raise ValueError(f"Node {node.get('id')} has no input named {name!r}")


def _output_slot(node: dict[str, Any], name: str) -> int:
    for index, item in enumerate(node.get("outputs", [])):
        if item.get("name") == name:
            return index
    raise ValueError(f"Node {node.get('id')} has no output named {name!r}")


def _new_node(
    template: dict[str, Any],
    node_id: int,
    title: str,
    position: tuple[float, float],
    widgets: list[Any] | None = None,
) -> dict[str, Any]:
    result = copy.deepcopy(template)
    result["id"] = node_id
    result["title"] = title
    result["pos"] = list(position)
    result["order"] = node_id
    if widgets is not None:
        result["widgets_values"] = widgets
    for item in result.get("inputs", []):
        item["link"] = None
    for item in result.get("outputs", []):
        item["links"] = []
    return result


def _runs(indices: Iterable[int]) -> list[tuple[int, int]]:
    values = list(indices)
    if not values:
        return []
    result: list[tuple[int, int]] = []
    start = previous = values[0]
    for value in values[1:]:
        if value != previous + 1:
            result.append((start, previous - start + 1))
            start = value
        previous = value
    result.append((start, previous - start + 1))
    return result


class SubgraphEditor:
    def __init__(self, subgraph: dict[str, Any]) -> None:
        self.subgraph = subgraph
        self.nodes: list[dict[str, Any]] = subgraph["nodes"]
        self.links: list[dict[str, Any]] = subgraph["links"]
        self.next_node_id = max(int(node["id"]) for node in self.nodes) + 1
        self.next_link_id = max(int(link["id"]) for link in self.links) + 1

    def add_node(self, node: dict[str, Any]) -> int:
        self.nodes.append(node)
        self.next_node_id = max(self.next_node_id, int(node["id"]) + 1)
        return int(node["id"])

    def allocate_node_id(self) -> int:
        result = self.next_node_id
        self.next_node_id += 1
        return result

    def add_link(
        self,
        origin_id: int,
        origin_slot: int,
        target_id: int,
        target_slot: int,
        value_type: str,
    ) -> int:
        link_id = self.next_link_id
        self.next_link_id += 1
        self.links.append(
            {
                "id": link_id,
                "origin_id": origin_id,
                "origin_slot": origin_slot,
                "target_id": target_id,
                "target_slot": target_slot,
                "type": value_type,
            }
        )
        return link_id

    def rebuild_references(self) -> None:
        node_map = {int(node["id"]): node for node in self.nodes}
        for node in self.nodes:
            for item in node.get("inputs", []):
                item["link"] = None
            for item in node.get("outputs", []):
                item["links"] = []
        for item in self.subgraph.get("inputs", []):
            item["linkIds"] = []
        for item in self.subgraph.get("outputs", []):
            item["linkIds"] = []

        for link in self.links:
            link_id = int(link["id"])
            origin_id = int(link["origin_id"])
            target_id = int(link["target_id"])
            if origin_id == -10:
                self.subgraph["inputs"][int(link["origin_slot"])]["linkIds"].append(link_id)
            else:
                origin = node_map[origin_id]
                origin["outputs"][int(link["origin_slot"])]["links"].append(link_id)
            if target_id == -20:
                outputs = self.subgraph.get("outputs", [])
                if isinstance(outputs, dict):
                    outputs = [outputs]
                    self.subgraph["outputs"] = outputs
                outputs[int(link["target_slot"])]["linkIds"].append(link_id)
            else:
                target = node_map[target_id]
                slot = int(link["target_slot"])
                if target["inputs"][slot].get("link") is not None:
                    raise ValueError(f"Input already linked: node={target_id}, slot={slot}")
                target["inputs"][slot]["link"] = link_id

        self.subgraph["state"]["lastNodeId"] = max(node_map)
        self.subgraph["state"]["lastLinkId"] = max(int(link["id"]) for link in self.links)


def _rebuild_top_level_references(workflow: dict[str, Any]) -> None:
    nodes = workflow["nodes"]
    node_map = {int(node["id"]): node for node in nodes}
    for node in nodes:
        for item in node.get("inputs", []):
            item["link"] = None
        for item in node.get("outputs", []):
            item["links"] = []
    for link in workflow["links"]:
        link_id, origin_id, origin_slot, target_id, target_slot, _type = link
        node_map[int(origin_id)]["outputs"][int(origin_slot)]["links"].append(int(link_id))
        target = node_map[int(target_id)]
        if target["inputs"][int(target_slot)].get("link") is not None:
            raise ValueError(f"Top-level input already linked: node={target_id}, slot={target_slot}")
        target["inputs"][int(target_slot)]["link"] = int(link_id)
    workflow["last_node_id"] = max(node_map)
    workflow["last_link_id"] = max(int(link[0]) for link in workflow["links"])


def _configure_top_level(workflow: dict[str, Any], mode: str) -> None:
    nodes = workflow["nodes"]
    subgraph_id = workflow["definitions"]["subgraphs"][0]["id"]
    group_node = next(node for node in nodes if node.get("type") == subgraph_id)
    load_images = [node for node in nodes if node.get("type") == "LoadImage"]
    if not load_images:
        raise ValueError("Source workflow has no LoadImage template")
    original_loader = copy.deepcopy(load_images[0])
    save_types = {"SaveVideo", "H3Idea2VideoProjectVideoSave"}
    save_nodes = {
        int(node["id"]): node for node in nodes if node.get("type") in save_types
    }
    final_link = next(
        (
            link
            for link in workflow["links"]
            if int(link[1]) == int(group_node["id"])
            and int(link[2]) == 0
            and int(link[3]) in save_nodes
        ),
        None,
    )
    if final_link is None:
        raise ValueError("Source workflow has no final video output link")
    save_node = save_nodes[int(final_link[3])]
    removed_node_ids = {
        int(node["id"])
        for node in nodes
        if node.get("type") == "LoadImage"
        or (node.get("type") in save_types and int(node["id"]) != int(save_node["id"]))
    }
    first_slot = _input_slot(group_node, "first_frame")
    last_slot = _input_slot(group_node, "last_frame")
    workflow["nodes"] = [node for node in nodes if int(node["id"]) not in removed_node_ids]
    workflow["links"] = [
        link
        for link in workflow["links"]
        if int(link[1]) not in removed_node_ids
        and int(link[3]) not in removed_node_ids
        and not (
            int(link[3]) == int(group_node["id"])
            and int(link[4]) in (first_slot, last_slot)
        )
    ]
    nodes = workflow["nodes"]
    group_node = next(node for node in nodes if int(node["id"]) == int(group_node["id"]))
    save_node = next(node for node in nodes if int(node["id"]) == int(save_node["id"]))
    group_node["outputs"] = group_node.get("outputs", [])[:1]

    group_node["title"] = f"MiniMax H3 {mode} — paste Prompt Studio output"
    group_node["widgets_values"][0] = GENERIC_PROMPTS[mode]
    save_node["type"] = "H3Idea2VideoProjectVideoSave"
    save_node["title"] = "Save directly to Idea2Video project / runs"
    save_node["inputs"] = [
        {
            "name": "video",
            "type": "VIDEO",
            "link": int(final_link[0]),
        },
        {
            "name": "project_root",
            "type": "STRING",
            "widget": {"name": "project_root"},
            "link": None,
        },
        {
            "name": "relative_path",
            "type": "STRING",
            "widget": {"name": "relative_path"},
            "link": None,
        },
        {
            "name": "crf",
            "type": "FLOAT",
            "widget": {"name": "crf"},
            "link": None,
        },
    ]
    save_node["outputs"] = [
        {
            "name": "receipt_json",
            "type": "STRING",
            "links": [],
        }
    ]
    save_node["widgets_values"] = [
        "$IDEA2VIDEO_PROJECT_ROOT",
        f"manual_exports/MiniMax_H3_{mode}_INT8_Turbo8_HQ_9x16_7s_1080p.mp4",
        18.0,
    ]

    if mode in ("I2VA", "FL2VA"):
        picture1 = copy.deepcopy(original_loader)
        picture1["id"] = int(original_loader["id"])
        picture1["title"] = "Picture 1 — first frame"
        picture1["widgets_values"] = ["Picture_1.png", "image"]
        picture1["pos"] = [60, 620]
        picture1["outputs"][0]["links"] = []
        nodes.append(picture1)
        next_link_id = max((int(link[0]) for link in workflow["links"]), default=0) + 1
        workflow["links"].append(
            [next_link_id, int(picture1["id"]), 0, int(group_node["id"]), first_slot, "IMAGE"]
        )

    if mode == "FL2VA":
        picture2 = copy.deepcopy(original_loader)
        picture2["id"] = max(int(node["id"]) for node in nodes) + 1
        picture2["title"] = "Picture 2 — last frame"
        picture2["widgets_values"] = ["Picture_2.png", "image"]
        picture2["pos"] = [60, 930]
        picture2["outputs"][0]["links"] = []
        nodes.append(picture2)
        next_link_id = max((int(link[0]) for link in workflow["links"]), default=0) + 1
        workflow["links"].append(
            [next_link_id, int(picture2["id"]), 0, int(group_node["id"]), last_slot, "IMAGE"]
        )

    notes = {
        "T2VA": (
            "## MiniMax H3 T2VA\n\nNo image is connected. Paste the complete T2VA prompt "
            "from H3 Prompt Studio into the prompt field. The 175 generated frames "
            "are uniformly remapped to 168 output frames, including generated frame 0."
        ),
        "I2VA": (
            "## MiniMax H3 I2VA\n\nLoad Picture 1 and paste the complete I2VA prompt from "
            "H3 Prompt Studio. Picture 1 conditions first_frame and also replaces "
            "output frame 0 after high-quality resizing. last_frame remains unconnected."
        ),
        "FL2VA": (
            "## MiniMax H3 FL2VA\n\nLoad Picture 1 and Picture 2, then paste the complete "
            "FL2VA prompt from H3 Prompt Studio. Both condition the model. The final "
            "168-frame sequence explicitly uses the exact pictures at frames 0 and 167, so the "
            "last-frame condition is never cropped away."
        ),
    }
    note = next(node for node in nodes if node.get("title") == "Note: MiniMax H3")
    size_note = next(node for node in nodes if node.get("title") == "Note: Size Settings Reference")
    note["widgets_values"] = notes[mode]
    size_note["widgets_values"] = (
        "Native generation: 768 x 1344\nModel frames: 175\nUniform output frames: 168\n"
        "Final video: 1080 x 1920\nFPS: 24\nExact duration: 7.000 seconds\n"
        "Sampling: Turbo v4, 8 steps\nH.264 10-bit, CRF 18\n"
    )
    _rebuild_top_level_references(workflow)


def _configure_subgraph(workflow: dict[str, Any], mode: str) -> None:
    subgraph = workflow["definitions"]["subgraphs"][0]
    subgraph["name"] = f"MiniMax H3 {mode} INT8 Turbo v4 8-step HQ 9x16 7s 1080p"
    nodes = subgraph["nodes"]
    selector_template = copy.deepcopy(
        next(node for node in nodes if node.get("type") == "ImageFromBatch")
    )
    batch_template = copy.deepcopy(
        next(node for node in nodes if node.get("type") == "ImageBatch")
    )
    condition_scale_template = copy.deepcopy(
        next(
            node
            for node in nodes
            if node.get("type") == "ImageScale"
            and "conditioning canvas" in str(node.get("title") or "").lower()
        )
    )
    exact_scale_template = copy.deepcopy(
        next(
            node
            for node in nodes
            if node.get("type") == "ImageScale"
            and "exact output frame 0" in str(node.get("title") or "").lower()
        )
    )
    h3_source = next(node for node in nodes if node.get("type") == "MiniMaxH3ImageToVideo")
    video_decode_source = next(node for node in nodes if node.get("type") == "VAEDecode")
    audio_decode_source = next(node for node in nodes if node.get("type") == "VAEDecodeAudio")
    upscale_loader_source = next(node for node in nodes if node.get("type") == "UpscaleModelLoader")
    upscale_source = next(node for node in nodes if node.get("type") == "ImageUpscaleWithModel")
    final_scale_source = next(
        node
        for node in nodes
        if node.get("type") == "ImageScale"
        and int(node["id"]) not in {int(condition_scale_template["id"]), int(exact_scale_template["id"])}
    )
    trim_audio_source = next(node for node in nodes if node.get("type") == "TrimAudioDuration")
    final_output_link = next(
        link
        for link in subgraph["links"]
        if int(link["target_id"]) == -20 and int(link["target_slot"]) == 0
    )
    final_video_source = _node(nodes, int(final_output_link["origin_id"]))
    if final_video_source.get("type") != "CreateVideo":
        raise ValueError("Subgraph output 0 is not produced by CreateVideo")

    retained_post_ids = {
        int(upscale_loader_source["id"]),
        int(upscale_source["id"]),
        int(final_scale_source["id"]),
        int(trim_audio_source["id"]),
        int(final_video_source["id"]),
    }
    removable_ids = {
        int(node["id"])
        for node in nodes
        if node.get("type") in {"ImageFromBatch", "ImageBatch"}
        or (
            node.get("type") == "ImageScale"
            and int(node["id"]) != int(final_scale_source["id"])
        )
        or (
            node.get("type") == "CreateVideo"
            and int(node["id"]) != int(final_video_source["id"])
        )
    }
    subgraph["nodes"] = [node for node in nodes if int(node["id"]) not in removable_ids]
    subgraph["links"] = [
        link
        for link in subgraph["links"]
        if int(link["origin_id"]) not in retained_post_ids | removable_ids
        and int(link["target_id"]) not in retained_post_ids | removable_ids
        and not (int(link["origin_id"]) == -10 and int(link["origin_slot"]) in (0, 1))
        and not (
            int(link["target_id"]) == int(h3_source["id"])
            and int(link["target_slot"])
            in (
                _input_slot(h3_source, "first_frame"),
                _input_slot(h3_source, "last_frame"),
            )
        )
    ]
    outputs = subgraph.get("outputs", [])
    if isinstance(outputs, list):
        subgraph["outputs"] = outputs[:1]

    editor = SubgraphEditor(subgraph)
    nodes = editor.nodes
    h3_node = _node(nodes, int(h3_source["id"]))
    h3_node["widgets_values"][0] = GENERIC_PROMPTS[mode]
    h3_node["widgets_values"][1:4] = [768, 1344, MODEL_FRAMES]

    # Keep stable IDs for the proven output nodes, but clear their old connections.
    upscale_loader = _node(nodes, int(upscale_loader_source["id"]))
    upscale = _node(nodes, int(upscale_source["id"]))
    final_scale = _node(nodes, int(final_scale_source["id"]))
    trim_audio = _node(nodes, int(trim_audio_source["id"]))
    create_video = _node(nodes, int(final_video_source["id"]))
    trim_audio["widgets_values"] = [0, DURATION_SECONDS]
    trim_audio["title"] = "Trim native audio to exactly 7 seconds"
    create_video["widgets_values"] = [FPS, 10]

    # The same nearest-position mapping is used for every mode. Exact reference
    # pictures replace the selected endpoints only after generation.
    if mode == "T2VA":
        generated_indices = SELECTED_INDICES
    elif mode == "I2VA":
        generated_indices = SELECTED_INDICES[1:]
    else:
        generated_indices = SELECTED_INDICES[1:-1]

    selector_ids: list[int] = []
    for run_index, (start, length) in enumerate(_runs(generated_indices)):
        node_id = editor.allocate_node_id()
        end = start + length - 1
        selector = _new_node(
            selector_template,
            node_id,
            f"Keep generated frames {start}-{end}",
            (-360, 5250 + run_index * 135),
            [start, length],
        )
        editor.add_node(selector)
        editor.add_link(
            int(video_decode_source["id"]),
            0,
            node_id,
            _input_slot(selector, "image"),
            "IMAGE",
        )
        selector_ids.append(node_id)

    current_source = selector_ids[0]
    current_slot = 0
    for batch_index, selector_id in enumerate(selector_ids[1:], start=1):
        node_id = editor.allocate_node_id()
        batch = _new_node(
            batch_template,
            node_id,
            f"Join remapped segment {batch_index + 1}",
            (20 + batch_index * 305, 5350 + batch_index * 85),
            [],
        )
        editor.add_node(batch)
        editor.add_link(current_source, current_slot, node_id, 0, "IMAGE")
        editor.add_link(selector_id, 0, node_id, 1, "IMAGE")
        current_source = node_id
        current_slot = 0

    editor.add_link(
        int(upscale_loader["id"]),
        _output_slot(upscale_loader, "UPSCALE_MODEL"),
        int(upscale["id"]),
        _input_slot(upscale, "upscale_model"),
        "UPSCALE_MODEL",
    )
    editor.add_link(
        current_source,
        current_slot,
        int(upscale["id"]),
        _input_slot(upscale, "image"),
        "IMAGE",
    )
    editor.add_link(
        int(upscale["id"]),
        _output_slot(upscale, "IMAGE"),
        int(final_scale["id"]),
        _input_slot(final_scale, "image"),
        "IMAGE",
    )
    final_scale["title"] = "Resize remapped generated frames to 1080x1920"

    exact_sources: dict[str, int] = {}
    if mode in ("I2VA", "FL2VA"):
        condition1_id = editor.allocate_node_id()
        condition1 = _new_node(
            condition_scale_template,
            condition1_id,
            "Picture 1 conditioning canvas 768x1344",
            (-1330, 5260),
            ["lanczos", 768, 1344, "center"],
        )
        editor.add_node(condition1)
        editor.add_link(-10, 0, condition1_id, 0, "IMAGE")
        editor.add_link(
            condition1_id,
            0,
            int(h3_node["id"]),
            _input_slot(h3_node, "first_frame"),
            "IMAGE",
        )

        exact1_id = editor.allocate_node_id()
        exact1 = _new_node(
            exact_scale_template,
            exact1_id,
            "Exact output frame 0 from Picture 1",
            (610, 6640),
            ["lanczos", 1080, 1920, "center"],
        )
        editor.add_node(exact1)
        editor.add_link(-10, 0, exact1_id, 0, "IMAGE")
        exact_sources["first"] = exact1_id

    if mode == "FL2VA":
        condition2_id = editor.allocate_node_id()
        condition2 = _new_node(
            condition_scale_template,
            condition2_id,
            "Picture 2 conditioning canvas 768x1344",
            (-980, 5260),
            ["lanczos", 768, 1344, "center"],
        )
        editor.add_node(condition2)
        editor.add_link(-10, 1, condition2_id, 0, "IMAGE")
        editor.add_link(
            condition2_id,
            0,
            int(h3_node["id"]),
            _input_slot(h3_node, "last_frame"),
            "IMAGE",
        )

        exact2_id = editor.allocate_node_id()
        exact2 = _new_node(
            exact_scale_template,
            exact2_id,
            "Exact output frame 167 from Picture 2",
            (950, 6640),
            ["lanczos", 1080, 1920, "center"],
        )
        editor.add_node(exact2)
        editor.add_link(-10, 1, exact2_id, 0, "IMAGE")
        exact_sources["last"] = exact2_id

    image_source = int(final_scale["id"])
    image_slot = _output_slot(final_scale, "IMAGE")
    if mode in ("I2VA", "FL2VA"):
        first_batch_id = editor.allocate_node_id()
        first_batch = _new_node(
            batch_template,
            first_batch_id,
            "Exact Picture 1 + uniformly remapped generated frames",
            (1280, 5500),
            [],
        )
        editor.add_node(first_batch)
        editor.add_link(exact_sources["first"], 0, first_batch_id, 0, "IMAGE")
        editor.add_link(image_source, image_slot, first_batch_id, 1, "IMAGE")
        image_source = first_batch_id
        image_slot = 0

    if mode == "FL2VA":
        final_batch_id = editor.allocate_node_id()
        final_batch = _new_node(
            batch_template,
            final_batch_id,
            "Append exact Picture 2 as output frame 167",
            (1590, 5500),
            [],
        )
        editor.add_node(final_batch)
        editor.add_link(image_source, image_slot, final_batch_id, 0, "IMAGE")
        editor.add_link(exact_sources["last"], 0, final_batch_id, 1, "IMAGE")
        image_source = final_batch_id
        image_slot = 0

    editor.add_link(
        image_source,
        image_slot,
        int(create_video["id"]),
        _input_slot(create_video, "images"),
        "IMAGE",
    )
    editor.add_link(
        int(audio_decode_source["id"]),
        0,
        int(trim_audio["id"]),
        _input_slot(trim_audio, "audio"),
        "AUDIO",
    )
    editor.add_link(
        int(trim_audio["id"]),
        0,
        int(create_video["id"]),
        _input_slot(create_video, "audio"),
        "AUDIO",
    )
    editor.add_link(int(create_video["id"]), 0, -20, 0, "VIDEO")
    editor.rebuild_references()


def validate_workflow(workflow: dict[str, Any], mode: str) -> list[str]:
    errors: list[str] = []
    top_nodes = {int(node["id"]): node for node in workflow.get("nodes", [])}
    top_link_ids = {int(link[0]) for link in workflow.get("links", [])}
    if len(top_link_ids) != len(workflow.get("links", [])):
        errors.append("duplicate top-level link ID")
    for link in workflow.get("links", []):
        link_id, origin_id, origin_slot, target_id, target_slot, _type = link
        if int(origin_id) not in top_nodes or int(target_id) not in top_nodes:
            errors.append(f"top-level dangling node in link {link_id}")
            continue
        if int(origin_slot) >= len(top_nodes[int(origin_id)].get("outputs", [])):
            errors.append(f"top-level invalid origin slot in link {link_id}")
        if int(target_slot) >= len(top_nodes[int(target_id)].get("inputs", [])):
            errors.append(f"top-level invalid target slot in link {link_id}")

    subgraph = workflow["definitions"]["subgraphs"][0]
    nodes = {int(node["id"]): node for node in subgraph["nodes"]}
    link_ids = {int(link["id"]) for link in subgraph["links"]}
    if len(link_ids) != len(subgraph["links"]):
        errors.append("duplicate subgraph link ID")
    for link in subgraph["links"]:
        link_id = int(link["id"])
        origin_id = int(link["origin_id"])
        target_id = int(link["target_id"])
        if origin_id != -10 and origin_id not in nodes:
            errors.append(f"subgraph dangling origin in link {link_id}")
        if target_id != -20 and target_id not in nodes:
            errors.append(f"subgraph dangling target in link {link_id}")

    h3 = next(node for node in nodes.values() if node.get("type") == "MiniMaxH3ImageToVideo")
    first_link = h3["inputs"][_input_slot(h3, "first_frame")].get("link")
    last_link = h3["inputs"][_input_slot(h3, "last_frame")].get("link")
    expected = {
        "T2VA": (False, False, 0),
        "I2VA": (True, False, 1),
        "FL2VA": (True, True, 2),
    }[mode]
    if bool(first_link) != expected[0] or bool(last_link) != expected[1]:
        errors.append(f"{mode} first/last frame connection mismatch")
    load_images = [node for node in top_nodes.values() if node.get("type") == "LoadImage"]
    if len(load_images) != expected[2]:
        errors.append(f"{mode} expected {expected[2]} LoadImage nodes")

    if h3["widgets_values"][1:4] != [768, 1344, MODEL_FRAMES]:
        errors.append("native resolution or frame count mismatch")
    lora = next(node for node in nodes.values() if node.get("type") == "MiniMaxH3TurboLoRA")
    if lora["widgets_values"][0] != "minimax_h3_turbo_v4_step600_ema.safetensors":
        errors.append("Turbo v4 LoRA mismatch")
    scheduler = next(node for node in nodes.values() if node.get("type") == "BasicScheduler")
    if scheduler["widgets_values"][1] != 8:
        errors.append("scheduler is not 8 steps")
    save = next(
        node
        for node in top_nodes.values()
        if node.get("type") == "H3Idea2VideoProjectVideoSave"
    )
    if save["widgets_values"][0] != "$IDEA2VIDEO_PROJECT_ROOT":
        errors.append("project output root token mismatch")
    if not str(save["widgets_values"][1]).endswith(".mp4"):
        errors.append("project output path mismatch")
    if float(save["widgets_values"][2]) != 18.0:
        errors.append("H.264/CRF 18 output mismatch")
    output_link = next(
        link
        for link in subgraph["links"]
        if int(link["target_id"]) == -20 and int(link["target_slot"]) == 0
    )
    create_video = nodes[int(output_link["origin_id"])]
    if create_video["widgets_values"] != [FPS, 10]:
        errors.append("FPS or bit depth mismatch")
    return errors


def build_workflow(source: dict[str, Any], mode: str) -> dict[str, Any]:
    if mode not in OUTPUT_FILENAMES:
        raise ValueError(f"Unsupported mode: {mode}")
    workflow = copy.deepcopy(source)
    _configure_top_level(workflow, mode)
    _configure_subgraph(workflow, mode)
    workflow.setdefault("extra", {})["h3_prompt_studio"] = {
        "mode": mode,
        "source_template": DEFAULT_SOURCE.name,
        "model_frames": MODEL_FRAMES,
        "output_frames": OUTPUT_FRAMES,
        "fps": FPS,
        "duration_seconds": DURATION_SECONDS,
        "selected_indices": SELECTED_INDICES,
        "dropped_indices": [
            index for index in range(MODEL_FRAMES) if index not in SELECTED_INDICES
        ],
        "endpoint_policy": {
            "T2VA": "generated endpoints",
            "I2VA": "exact Picture 1 at output frame 0",
            "FL2VA": "exact Picture 1 at frame 0 and exact Picture 2 at frame 167",
        }[mode],
        "project_output": {
            "root": "$IDEA2VIDEO_PROJECT_ROOT",
            "directory": "runs/manual_exports",
            "node": "H3Idea2VideoProjectVideoSave",
        },
    }
    errors = validate_workflow(workflow, mode)
    if errors:
        raise ValueError("; ".join(errors))
    return workflow


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()

    source_path = args.source.resolve()
    output_dir = args.output_dir.resolve()
    if not source_path.is_file():
        raise SystemExit(f"Source workflow not found: {source_path}")
    output_dir.mkdir(parents=True, exist_ok=True)
    with source_path.open("r", encoding="utf-8") as handle:
        source = json.load(handle)

    for mode, filename in OUTPUT_FILENAMES.items():
        workflow = build_workflow(source, mode)
        destination = output_dir / filename
        with destination.open("w", encoding="utf-8", newline="\n") as handle:
            json.dump(workflow, handle, ensure_ascii=False, indent=2)
            handle.write("\n")
        print(f"Built {mode}: {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
